config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resource :imports
    resources :rounds do
      post :activate, on: :member
      post :deactivate, on: :member
      post :complete, on: :member
      post :continue, on: :member
      get "answers", on: :member
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :game
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions

  validates :category, presence: true

  def round_number
    position + 1
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :load_game
  before_action :load_game_round, except: :new
  
  def new
    @round = @game.new_round(category: "")
  end

  def show
  end

  def edit
  end

  def answers
  end

  def create
    @round = @game.rounds.build(round_params)
    if @round.save
      respond_to do |format|
        format.html { redirect_to(new_game_round_path(@game)) }
        format.json { render json: { message: "Saved" } }
      end
    else
      respond_to do |format|
        format.html { render "new" }
        format.json { render json: { error: @round.errors } }
      end
    end
  end

  def update
    if @round.update(round_params)
      respond_to do |format|
        format.html { redirect_to @round.game }
        format.json { render json: { message: "Saved" } }
      end
    else
      respond_to do |format|
        format.json { render json: { error: @round.errors } }
      end
    end
  end

  def activate
    if @round.valid?
      if !@round.active
        @round.update(active: true)
        redirect_to @game, notice: "Round #{@round.category} actived"
      else
        redirect_to @game, notice: "Round #{@round.category} is already active"
      end
    else
      redirect_to @game, notice: "Game or round not found..."
    end
  end

  def deactivate
    if @round.valid?
      if @round.active
        @round.update(active: false)
        redirect_to @game, notice: "Round #{@round.category} deactivated"
      else
        redirect_to @game, notice: "Round #{@round.category} has already been deactivated"
      end
    else
      redirect_to @game, notice: "Game or round not found..."
    end
  end

  def complete
    if @round.valid?
      if !@round.completed
        @round.update(completed: true)
        redirect_to @game, notice: "Round #{@round.category} completed"
      else
        redirect_to @game, notice: "Round #{@round.category} has already been set to complete"
      end
    else
      redirect_to @game, notice: "Game or round not found..."
    end
  end

  def continue
    if @round.valid?
      if @round.completed
        @round.update(completed: false)
        redirect_to @game, notice: "Round #{@round.category} continuing"
      else
        redirect_to @game, notice: "Round #{@round.category} has already been set to continue"
      end
    else
      redirect_to @game, notice: "Game or round not found..."
    end
  end
  
  private

  def round_params
    params.require(:round).permit(:position, :category, :game_id, questions_attributes: [:text, :url, :answer, :position])
  end

  def load_game
    @game = Game.find_by(id: params[:game_id])
  end
  
  def load_game_round
    @round_number = params[:id].to_i
    @round = @game.rounds.by_round(@round_number).first
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_audio_fields.html.erb
<div class="mb-3">
    <%= form.label :url, "Image or Audio URL", class: "form-label"  %>
    <%= form.text_field :url, class: "form-control" %>
    <%= form.label :answer, "Answer", class: "form-label"  %>
    <%= form.text_field :answer, class: "form-control" %
</div>

app/views/rounds/_form.html.erb
<%= form_with(model: [round.game, round]) do |form| %>
  <%= form.hidden_field :game_id %>
  <%= form.hidden_field :position %>
    <div class="mb-3 col-10">
      <%= form.label :category, class: "form-label" %>
      <%= form.text_field :category, class: "form-control" %>
    </div>
    <div class="mb-3 col-10">
      <%= form.label :round_type, "Round Type", class: "form-label" %>
      <%= form.select :round_type, [["Question Round", "question"], ["Audio Round", "audio"], ["Picture Round", "image"], ["Final Round", "order"]], class: "form-select" %>
    </div>

  <h3>Questions</h3>

<div class="row">
  <div class="col-10">
    <div class="card">
      <div class="card-body">
        <ul class="list-unstyled sortable">
          <%= form.fields_for :questions, round.questions do |question_form| %>
            <li class="sort">
              <div class="row">
                <div class="col-sm-1">
                 <i class="fas fa-bars handle"></i> 
                </div>
                <div class="col-sm-11">
                  <%= question_form.hidden_field :position %>
                  <%= render "#{round.round_type}_fields", form: question_form %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

  <%= form.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/rounds/_image_fields.html.erb
<div class="mb-3">
    <%= form.label :url, "Image", class: "form-label"  %>
    <%= form.file_field :picture, class: "form-control" %>
    <%= form.label :answer, "Answer", class: "form-label"  %>
    <%= form.text_field :answer, class: "form-control" %>
</div>

app/views/rounds/_order_fields.html.erb
<div class="mb-3">
    <%= form.label :text, "Question Text", class: "form-label"  %>
    <%= form.text_field :text, class: "form-control" %>
    <%= form.label :answer, "Answer", class: "form-label"  %>
    <%= form.text_field :answer, class: "form-control" %
</div>

app/views/rounds/_overview.html.erb
<div class="row">
  <div class="col-11">
    <h3>Round <%= round.position + 1 %> - <%= round.category %></h3>
  </div>
  <div class="col-1">
    <%= link_to "Edit", edit_game_round_path(round.game, round) %>
  </div>
</div>

app/views/rounds/_question_fields.html.erb
<div class="mb-3">
    <%= form.label :text, "Question Text", class: "form-label"  %>
    <%= form.text_field :text, class: "form-control" %>
    <%= form.label :answer, "Answer", class: "form-label"  %>
    <%= form.text_field :answer, class: "form-control" %>
</div>

app/views/rounds/answers.html.erb
<div class="row">
  <div class="col-12 my-4 d-flex justify-content-start">
    <h1 class="col-10">
      <% if @round_number == @game.rounds.count %>
        Final Round - <%= @round.category %> Answers
      <% else %>
        Round <%= @round_number %> - <%= @round.category %> Answers
      <%end %>
    </h1>
  </div>
</div>
<% if @round.active && @round.completed %>
  <div class="row">
    <% if @round.round_type == "image" %>
      <% @round.questions.each_with_index do |question, index|%>
        <div class="col-3">
          <div class="card text-center" >
            <%= image_tag question.url, class: "card-img-top" %>
            <div class="card-footer" class="card-text"><%= question.answer %></div>
          </div>
        </div>
      <% end%>
    <% elsif @round.round_type == "audio" %>
      <% @round.questions.each_with_index do |question, index| %>
        <div class="col-3 my-4">
          <div class="card text-center">
            <div class="card-header" class="card-text">Question <%= index+1 %></div>
            <div class="card-body"> <%= audio_tag question.url, class: "card-img-top", controls: true %></div>
            <div class="card-footer" class="card-text"><%= question.answer %></div>
          </div>
        </div>
      <% end %>
    <% elsif @round.round_type == "order" %>
        <div class="col-12 my-4">
          <div class="card">
            <div class="card-header" class="card-text">Final Question</div>
            <div class="card-body">
              <h5 class="card-title"><%= @round.questions.first.text %></h5>
              <div class="card-text">
                <ol class="px-5">
                <% @round.questions.first.answer.split(",").each do |answer_number| %>
                  <li class="my-4"><%= @round.questions[answer_number.to_i].text %> (<%= @round.questions[answer_number.to_i].answer %>)</li>
                <% end %>
                <ol>
              </div>
            </div>
          </div>
        </div>
    <% else %>
      <div class="row-12">
        <% @round.questions.each_with_index do |question, index| %>
        <div class="card text-white bg-secondary my-4">
          <div class="card-header">Question <%= index + 1 %></div>
          <div class="card-body blockquote"><%= question.text %></div>
          <div class="card-footer blockquote"><%= question.answer %></div>
        </div>
        <% end%>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="row">
    <div class="col-10 offset-1">
      <div class="card text-center">
        <div class="card-header display-3">Wait a Minute, Bub!</div>
        <div class="card-body lead align-middle" style="min-height: 400px">
          <div class="mt-5">
            <img src="https://static1.cbrimages.com/wordpress/wp-content/uploads/2020/10/Wolverine-X-of-Swords-header.jpg" height="250" alt="Wolverine blocking your passage" />
          </div>
        This Round is not yet active.  No cheating!
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/rounds/edit.html.erb
<div class="row">
  <div class="col">
    <h1>Editing Round <%= @round.position + 1 %></h1>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <%= render "rounds/form", round: @round %>
  </div>
</div>

app/views/rounds/new.html.erb
<h1>Game <%= @game.name %> | New Round</h1>

<% unless  @round.errors.empty? %>
  <div><%= @round.errors.full_messages.join(", ") %></div>
<% end %>
<%= render "form", round: @round %>

app/views/rounds/show.html.erb
<div class="row">
  <div class="col-12 my-4 d-flex justify-content-start">
    <div class="col-1">
      <% if @round_number > 1 %>
        <%= link_to(content_tag(:span, "", class: "carousel-control-prev-icon").html_safe, game_round_path(@game, @round_number - 1)) %>
      <% end%>
    </div>
    <h1 class="col-10">
    <% if @round_number == @game.rounds.count %>
      Final Round - <%= @round.category %>
    <% else %>
      Round <%= @round_number %> - <%= @round.category %>
    <%end %>
    </h1>
    <div class="col-1">
      <% if @round_number < @game.rounds.count %>
        <%= link_to(content_tag(:span, "", class: "carousel-control-next-icon").html_safe, game_round_path(@game, @round_number + 1)) %>
      <% end %>
    </div>
  </div>
</div>
<% if @round.active %>
  <div class="row">
    <% if @round.round_type == "image" %>
      <% @round.questions.each_with_index do |question, index|%>
        <div class="col-3">
          <div class="card text-center" >
          <% if question.picture %>
            <%= image_tag url_for(question.picture), class: "card-img-top" %>
          <% end %>
            <div class="card-footer" class="card-text">Question <%= index+1 %></div>
          </div>
        </div>
      <% end%>
    <% elsif @round.round_type == "audio" %>
      <% @round.questions.each_with_index do |question, index| %>
        <div class="col-3 my-4">
          <div class="card text-center">
            <div class="card-header" class="card-text">Question <%= index+1 %></div>
            <div class="card-body"> <%= audio_tag question.url, class: "card-img-top", controls: true %></div>
          </div>
        </div>
      <% end %>
    <% elsif @round.round_type == "order" %>
        <div class="col-12 my-4">
          <div class="card">
            <div class="card-header" class="card-text">Final Question</div>
            <div class="card-body">
              <h5 class="card-title"><%= @round.questions.first.text %></h5>
              <div class="card-text">
                <ol class="px-5">
                <% @round.questions[1..-1].each do |question| %>
                  <li class="my-4"><%= question.text %></li>
                <% end %>
                <ol>
              </div>
            </div>
          </div>
        </div>
    <% else %>
      <div class="row-12">
        <% @round.questions.each_with_index do |question, index| %>
        <div class="card text-white bg-secondary my-4">
          <div class="card-header">Question <%= index + 1 %></div>
          <div class="card-body blockquote"><%= question.text %></div>
        </div>
        <% end%>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="row">
    <div class="col-10 offset-1">
      <div class="card text-center">
        <div class="card-header display-3">Wait a Minute, Bub!</div>
        <div class="card-body lead align-middle" style="min-height: 400px">
          <div class="mt-5">
            <img src="https://static1.cbrimages.com/wordpress/wp-content/uploads/2020/10/Wolverine-X-of-Swords-header.jpg" height="250" alt="Wolverine blocking your passage" />
          </div>
        This Round is not yet active.  No cheating!
        </div>
      </div>
    </div>
  </div>
<% end %>