config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resource :imports
    resources :rounds do
      post :activate, on: :member
      post :deactivate, on: :member
      post :complete, on: :member
      post :continue, on: :member
      get "answers", on: :member
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def new
    @game = Game.find(params[:game_id]) 
    @importer = TriviaImporter.new(game: @game)
  end

  def create
    @game = Game.find(params[:game_id])
    @importer = TriviaImporter.new(game: @game, file: importer_params[:file].tempfile)
    if @importer.import
      @game.save
      redirect_to edit_game_path(@game), notice: "Trivia questions imported!"
    else
      flash[:error] = "Could not import trivia questions!"
      render 'new'
    end
  end

  def importer_params
    params.require(:trivia_importer).permit(:file)
  end
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/imports/new.html.erb
<div class="row">
    <div class="col-12">
        <h3>Import Trivia Questions</h3>
    </div>
</div>
<div class="row">
  <div class="col-12">
    <%= form_for @importer, url: game_imports_path(@game), multipart: true do |f| %>
      <%= f.label :file, "Trivia PDF" %>
      <%= f.file_field :file, accept: "application/pdf" %>
      <%= f.submit "Import"%>
    <% end %>
  </div>
</div>