config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resource :imports
    resources :rounds do
      post :activate, on: :member
      post :deactivate, on: :member
      post :complete, on: :member
      post :continue, on: :member
      get "answers", on: :member
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :rounds, dependent: :destroy do
    def by_round(round_number)
      where(position: round_number - 1)
    end
  end

  def new_round(category:, question_count: 10)
    round = rounds.build(position: self.rounds.length, category: category)
    question_count.times do |position|
      round.questions.build(position: position)
    end

    round
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
    #@game.new_round(category: "")
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<div class="card">
  <%= form_with(model: game, class: "card-body") do |form| %>
    <% if game.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

        <ul>
          <% game.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Create", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/games/edit.html.erb
<div class="row">
  <div class="col">
    <h1>Editing Game</h1>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <%= render 'form', game: @game %>
  </div>
</div>

<div class="row">
  <div class="col">
    <h3>Game Rounds</h3>
  </div>
</div>
<% if @game.rounds.any?%>
  <% @game.rounds.each do |round| %>
    <%= render "rounds/overview", round: round %>
  <% end %>
<% else %>
  <div class="row">
    <div class="col">
      No categories added yet.  <%= link_to "Add a category", new_game_round_path(@game) %> or <%= link_to "Import a PDF", new_game_imports_path(@game) %>.
    </div>
  </div>
<% end %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Played at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.played_at %></td>
        <td><%= button_to 'Show', game, method: :get %></td>
        <td><%= button_to 'Edit', edit_game_path(game), method: :get %></td>
        <td><%= button_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<div class="row">
  <div class="col">
    <h1>New Game</h1>
  </div>
</div>
<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Played at:</strong>
  <%= @game.played_at %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

<p>
  <% @game.rounds.each do |round| %>
    <p><%= round.category %></p>
    <% if !round.active %>
      <p><%= button_to "Activate", activate_game_round_path(@game, round.round_number) %></p>
    <% else %>
      <p><%= button_to "Deactivate", deactivate_game_round_path(@game, round.round_number) %></p>
    <% end %>
    <% if !round.completed %>
      <p><%= button_to "Complete", complete_game_round_path(@game, round.round_number) %></p>
    <% else %>
      <p><%= button_to "Continue", continue_game_round_path(@game, round.round_number) %></p>
    <% end %>
  <% end %>
</p>